version: "3.8"

services:
  # sudokusolver:
  #   build:
  #     context: .
  #     network: "host"
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./website:/website
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - db
  #   environment:
  #     DB_URI: ${DB_URI}
  
  db:
    image: postgres:16.0-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
