version: "3.7"
services:
 api:
  build:
   context: .
   network: "host"
   dockerfile: Dockerfile
  volumes:
   - ./:/website
   - /website/node_modules
  ports:
   - 3000:3000
  command: npm run dev
