version: "3.8"

services:
  sudokusolver:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./website/app:/website/app
      - ./website/public:/website/public
    ports:
      - 3000:3000
    depends_on:
      - db
  
  db:
    image: postgres:16.0-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
